config/routes.rb
require 'sidekiq/web'
require 'redmine_sidekiq/admin_constraint'

RedmineApp::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => RedmineSidekiq::AdminConstraint.new

  match '/sidekiq/sandbox', to: 'sidekiq_sandbox#index', via: :get
  match '/sidekiq/sandbox/perform_async', to: 'sidekiq_sandbox#perform_async', via: :post
  match '/sidekiq/sandbox/perform_in', to: 'sidekiq_sandbox#perform_in', via: :post
  match '/sidekiq/sandbox/perform_at', to: 'sidekiq_sandbox#perform_at', via: :post
end

app/controllers/sidekiq_sandbox_controller.rb
class SidekiqSandboxController < ApplicationController
  unloadable
  before_filter :require_admin

  def index
    @stats = Sidekiq::Stats.new
  end

  def perform_async
    name = params['name']
    count = params['count']
    jid = SandboxWorker.perform_async(name, count)
    flash[:notice] = "Enqueued job id: #{jid}" if jid
    redirect_to :action => 'index'
  end

  def perform_in
    interval = params['interval'].to_i ||= 2
    jid = SandboxWorker.perform_in(interval.minute)
    flash[:notice] = "Enqueued job id: #{jid}" if jid
    redirect_to :action => 'index'
  end

  def perform_at
    interval = params['interval'].to_i ||= 2
    jid = SandboxWorker.perform_at(interval.minute.from_now)
    flash[:notice] = "Enqueued job id: #{jid}" if jid
    redirect_to :action => 'index'
  end
end

app/helpers/sidekiq_sandbox_helper.rb
module SidekiqSandboxHelper
end

app/views/sidekiq_sandbox/index.html.erb
<h2><%= l :sidekiq %></h2>
<h3>Sandbox</h3>

<hr>

<h4>Stats</h4>

<div class="box">stats = Sidekiq::Stats.new</div>

<p>Gets the number of jobs that have been processed.</p>
<div class="box">stats.processed # => <%= @stats.processed %></div>

<p>The number of jobs that have failed.</p>
<div class="box">stats.failed # => <%= @stats.failed %></div>

<p>The queues with name and number enqueued.</p>
<div class="box">stats.queues # => <%= @stats.queues %></div>

<p>The number of jobs enqueued in all queues (does NOT include retries and scheduled jobs).</p>
<div class="box">stats.enqueued # => <%= @stats.enqueued %></div>

&nbsp;

<h4>Jobs</h4>

<p>The standard.</p>
<div class="box"><%= link_to('perform_async(*args)', sidekiq_sandbox_perform_async_path, method: :post) %></div>

<p>The Scheduled Jobs by interval.</p>
<div class="box"><%= link_to('perform_in(interval, *args)', sidekiq_sandbox_perform_in_path(interval: 1), method: :post) %></div>

<p>The Scheduled Jobs by timestamp.</p>
<div class="box"><%= link_to('perform_at(timestamp, *args)', sidekiq_sandbox_perform_at_path(interval: 1), method: :post) %></div>

<p>The job will fail.</p>
<div class="box"><%= link_to('perform_async()', sidekiq_sandbox_perform_async_path(name: :failed), method: :post) %></div>